spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/transaction?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2b8
    username: root

fkh:
  mybatis:
    enable-sql-explain-interceptor: true
    performmax-time: 2
    sql-format: false
